baseurl = "/"
languageCode = "es-ar"
title = "El Radar"
theme = "hugo-theme-terminal"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Acerca de"
    url = "/about/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/_elradar_"

[params]
    description = "Proyectos basados en R que tenés que conocer"
    fullWidthTheme = false
    centerTheme = false
    
    # opciones del theme terminal
    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "blue"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

